DROP TABLE IF EXISTS SYS_CONFIG;

CREATE TABLE SYS_CONFIG
(
	SERVICE_NAME VARCHAR(32) NOT NULL COMMENT '服务名',
	ENV VARCHAR(16) NULL DEFAULT 'dev' COMMENT '环境，如dev prod test',
	PROPERTY_KEY VARCHAR(128) NOT NULL COMMENT '属性KEY',
	PROPERTY_VALUE VARCHAR(128) NULL DEFAULT NULL COMMENT '属性值',
	PROPERTY_DEFAULT_VALUE VARCHAR(50) NULL DEFAULT NULL COMMENT '属性默认值',
	REMARK VARCHAR(50) NULL DEFAULT NULL COMMENT '备注',
	LABEL VARCHAR(50) NOT NULL DEFAULT 'master' COMMENT '标签'
);